// src/routes/(align)/(admin)/admin/+page.svelte
<script lang="ts">
    import { page } from "$app/state";

    const user = page.data.user!;
</script>

<h4>Dashboard</h4>

<h2>Profile</h2>
<hr />

<h3>Hello, {user?.name}!</h3>
<h4>Sign out</h4>
<form class="mb-4" method="POST" action="/auth/signout">
    <button class="btn">Sign out</button>
</form>
<h4>Settings</h4>
<p><a class="btn" href="settings">Settings</a></p>
<!-- {#if user.admin}
    <div class="p-4 border-2 border-gray-300 rounded-2xl bg-gray-500/10">
        <h4>Admin</h4>
        <p>You are an administrator.</p>
        <p>
            <a class="btn" href="/admin">Admin dashboard</a>
        </p>
    </div>
{/if} -->

// app/admin/page.tsx
import { getSessionUserProfile } from "@/app/lib/session";
import { signOut } from "@/auth";
import { notFound } from "next/navigation";
import prisma from "@/app/lib/database";

export default async function AdminPage() {
    const { session, user, profile } = await getSessionUserProfile();
    if (!session || !user || user.role < 5 || !profile) {
        return notFound();
    }
    return (
        <main>
            <div className="py-16 text-5xl text-center text-cyan-800">
                Hello, {profile.name}!
                <br />
                Logged in as {user.email} (admin)
                <br />
                <form
                    action={async () => {
                        "use server";
                        await signOut();
                    }}
                >
                    <button>Sign out</button>
                </form>
            </div>
            <div>
                <h2>Admin tools</h2>
                <ul>
                    {(await prisma.user.findMany()).map(user => (
                        <li key={user.id}>
                            {user.email} {user.role}
                        </li>
                    ))}
                </ul>
            </div>
        </main>
    );
}
