// app/ui/footer.tsx
import Link from "next/link";
import Image from "next/image";
import InstagramLogo from "/public/social/instagram.png";

export default function Footer() {
    return (
        <footer id="contact" className="px-8 bg-gray-900">
            <div className="m-auto w-full max-w-5xl">
                <Contact />
                <hr className="border-neutral-600" />
                <Legal />
            </div>
        </footer>
    );
}

function Contact() {
    return (
        <div className="flex max-sm:flex-col py-6">
            <div className="grow min-w-80">
                <h2 className="text-lg font-serif uppercase tracking-widest text-cyan-100/80">
                    Contact
                </h2>
                <div className="py-4 font-mono text-neutral-200">
                    <p>
                        <Link
                            className="hover:underline"
                            href="mailto:tabulamusica@cambridgesu.co.uk"
                        >
                            tabulamusica@cambridgesu.co.uk
                        </Link>
                    </p>
                    <p>
                        <Link
                            className="group"
                            href="https://www.instagram.com/tabula_musica"
                        >
                            <Image
                                className="inline"
                                src={InstagramLogo}
                                alt="Instagram logo"
                                width={20}
                            />{" "}
                            <span className="group-hover:underline">
                                @tabula_musica
                            </span>
                        </Link>
                    </p>
                </div>
            </div>
            <div className="grow">
                <h3 className="text-lg font-serif uppercase tracking-widest text-cyan-100/80">
                    Subscribe
                </h3>
                <div className="flex sm:max-md:flex-col gap-4 py-4 text-lg text-neutral-200">
                    <p>
                        <Link
                            className="px-4 py-2 rounded-full tracking-wider font-serif text-cyan-800 transition-colors bg-amber-100 hover:bg-amber-100/90"
                            href="https://lists.srcf.net/mailman/listinfo"
                        >
                            Mailing&nbsp;List
                        </Link>
                    </p>
                    <p>
                        <Link
                            className="px-4 py-2 rounded-full tracking-wider font-serif text-cyan-800 transition-colors bg-amber-100 hover:bg-amber-100/90"
                            href="/#contact"
                        >
                            Magazine
                        </Link>
                    </p>
                </div>
            </div>
        </div>
    );
}

function Legal() {
    return (
        <p className="py-4 text-xs font-mono tracking-wide text-neutral-400">
            © 2024 Tabula Musica. All rights reserved.
        </p>
    );
}

// src/lib/components/footer/Footer.svelte
<script>
	import Contact from '$lib/components/footer/grid/Contact.svelte';
	import Donate from '$lib/components/footer/grid/Donate.svelte';
	import Social from '$lib/components/footer/grid/Social.svelte';
	import Subscribe from '$lib/components/footer/grid/Subscribe.svelte';
	import Legal from '$lib/components/footer/Legal.svelte';
</script>

<footer class="bg-gray-900">
	<div class="util-restrict px-6">
		<div class="grid sm:grid-cols-2 py-6 gap-8">
			<Subscribe />
			<Contact />
			<Social />
			<Donate />
		</div>
		<hr class="border-neutral-600" />
		<Legal />
	</div>
</footer>

<style lang="postcss">
	footer :global(h5) {
		@apply uppercase text-cyan-100;
	}

	footer :global(.button) {
		@apply inline-flex h-10 px-4 items-center
        text-cyan-800
        transition-colors bg-amber-100 hover:bg-amber-100/80
        rounded-full tracking-wider;
	}
</style>
