// app/login/page.tsx
import { SignInCredentials, SignUpCredentials, signIn, signUp } from "@/auth";
import prisma from "@/app/lib/database";
import { redirect } from "next/navigation";

export default function LoginPage() {
    async function handleSignIn(formData: FormData) {
        "use server";
        const credentials: SignInCredentials = {
            email: formData.get("email") as string,
            password: formData.get("password") as string,
        };
        const user = await signIn(credentials);
        if (user) redirect("/profile");
    }

    async function handleSignUp(formData: FormData) {
        "use server";
        const credentials: SignUpCredentials = {
            email: formData.get("email") as string,
            password: formData.get("password") as string,
            confirmPassword: formData.get("confirmPassword") as string,
            name: formData.get("name") as string,
            mailingList: formData.get("mailingList") === "on",
        };
        const user = await signUp(credentials);
        if (user) redirect("/profile");
    }

    return (
        <main>
            <div className="p-32">
                <form action={handleSignIn}>
                    <input
                        type="email"
                        name="email"
                        placeholder="Email"
                        required
                    />
                    <br />
                    <input
                        type="password"
                        name="password"
                        placeholder="Password"
                        defaultValue="password"
                        required
                    />
                    <br />
                    <button>Log in</button>
                </form>
                <br />
                <form action={handleSignUp}>
                    <input
                        type="email"
                        name="email"
                        placeholder="Email"
                        defaultValue="newuser@example.com"
                        required
                    />
                    <br />
                    <input
                        type="password"
                        name="password"
                        placeholder="Password"
                        defaultValue="password"
                        required
                    />
                    <br />
                    <input
                        type="password"
                        name="confirmPassword"
                        placeholder="Confirm password"
                        defaultValue="password"
                        required
                    />
                    <br />
                    <input
                        type="text"
                        name="name"
                        placeholder="Name"
                        defaultValue="Jane Doe"
                        required
                    />
                    <br />
                    Would you like to subscribe to our mailing list?
                    <br />
                    <input type="checkbox" name="mailingList" />
                    <br />
                    <button>Sign up</button>
                </form>
            </div>

            <button
                onClick={async () => {
                    "use server";
                    await prisma.reset();
                }}
            >
                Reset database
            </button>
        </main>
    );
}

// src/routes/(align)/login/+page.svelte
<script lang="ts">
	// import { signIn } from '@auth/sveltekit/client';
	import { enhance } from '$app/forms';
</script>

<h3>Log in</h3>

<section class="flex max-sm:flex-col gap-4">
	<div class="grow">
		<form method="POST" action="?/signin" use:enhance>
			<input class="input" type="text" name="email" placeholder="Email" required />
			<input class="input" type="password" name="password" placeholder="Password" required />
			<button class="btn mb-4">Log in</button>
		</form>
	</div>

	<div class="grow">
		<h5>University sign in</h5>

		<form action="/auth/google">
			<button class="btn mb-4"> Sign in with Raven </button>
		</form>
	</div>
</section>

<h3>Sign up</h3>
<form method="POST" action="/auth/credentials/signup" use:enhance>
	<input class="input" type="text" name="email" placeholder="Email" required />
	<input class="input" type="password" name="password" placeholder="Password" required />
	<input
		class="input"
		type="password"
		name="confirmPassword"
		placeholder="Confirm password"
		required
	/>
	<input class="input" type="text" name="name" placeholder="Name" required />
	<label class="block">
		<input class="size-4" type="checkbox" name="mailingList" />
		Subscribe to mailing list
	</label>
	<button class="btn mb-4">Sign up</button>
</form>
