// src/routes/(protected)/profile/+page.svelte
<script lang="ts">
	import { page } from '$app/stores';
	import { signOut } from '@auth/sveltekit/client';

	const user = $page.data.session?.user;
</script>

<h2>Profile</h2>
<hr />

<section>
	<p>Hello, {user?.name}!</p>
	<p>
		Logged in as {user?.email}
	</p>
	<h4>Sign out</h4>
	<p><button on:click={() => signOut()}>Sign out</button></p>
	{#if true}
		<h4>Admin</h4>
		<p><a href="/admin">Go to admin page</a></p>
	{/if}
	<h4 class="">Settings</h4>
	<p><a href="settings">Go</a></p>
</section>

// app/profile/page.tsx
import { getSessionUserProfile } from "@/app/lib/session";
import { signOut } from "@/auth";

export default async function ProfilePage() {
    const { user, profile } = await getSessionUserProfile();

    if (!user || !profile) {
        return (
            <main>
                <div className="py-16 text-5xl text-center text-cyan-800">
                    Please sign in:
                    <br />
                    <form>
                        <a href="/login">Sign in</a>
                    </form>
                </div>
            </main>
        );
    }

    return (
        <main>
            <div className="py-16 text-5xl text-center text-cyan-800">
                Hello, {profile.name}!
                <br />
                Logged in as {user.email}
                <br />
                <form
                    action={async () => {
                        "use server";
                        await signOut();
                    }}
                >
                    <button>Sign out</button>
                </form>
            </div>
        </main>
    );
}
