// src/lib/components/Footer.svelte
<footer class="bg-gray-900">
	<div class="mx-auto max-w-6xl px-6">
		<div class="grid sm:grid-cols-2 py-6 gap-8">
			<!-- <hgroup class="grow">
				<h4 class="mb-4 text-lg uppercase tracking-widest text-cyan-100">Subscribe</h4>
				<p class="mb-4 text-gray-200">From £0/month</p>
				<div class="flex flex-wrap gap-4">
					<button>Mailing list</button>
					<button>Paper edition</button>
				</div>
			</hgroup>
			<hgroup class="grow">
				<h4 class="mb-4 text-lg uppercase tracking-widest text-cyan-100">Write</h4>
				<p class="mb-4 text-gray-200">Become an editor maybe</p>
				<button>Apply</button>
			</hgroup> -->
			<hgroup class="grow">
				<h4 class="mb-4 text-lg uppercase tracking-widest text-cyan-100">Contact</h4>
				<p class="mb-4 text-gray-200">Have any questions, or fancy writing for us?</p>
				<button>Contact</button>
			</hgroup>
			<hgroup class="grow">
				<h4 class="mb-4 text-lg uppercase tracking-widest text-cyan-100">Social</h4>
				<p>
					<img
						class="inline mr-1 size-4"
						src="/icons/instagram.png"
						alt="Instagram logo"
						width={20}
					/>
					<a
						class="tracking-wide transition-colors text-gray-200 hover:text-white"
						href="https://www.instagram.com/tabula_musica"
					>
						@tabula_musica
					</a>
				</p>
				<p>
					<img class="inline mr-1 size-4" src="/icons/email.png" alt="Email icon" />
					<a
						class="tracking-wide transition-colors text-gray-200 hover:text-white"
						href="mailto:tabulamusica@cambridgesu.co.uk"
					>
						tabulamusica@cambridgesu.co.uk
					</a>
				</p>
			</hgroup>
			<hgroup class="grow">
				<h4 class="mb-4 text-lg uppercase tracking-widest text-cyan-100">Donate</h4>
				<p class="mb-4 text-gray-200">Give money</p>
				<button>Donate</button>
			</hgroup>
			<!-- Donate button -->
		</div>
		<hr class="mb-4 border-neutral-600" />
		<ul class="mb-4 flex gap-x-8 text-sm text-gray-400">
			<li>
				<a href="/about">About</a>
			</li>
			<li>
				<a href="/privacy-policy">Privacy policy</a>
			</li>
			<li>
				<a href="/cookies">Cookies</a>
			</li>
			<li>
				<a href="/advertising">Advertising</a>
			</li>
		</ul>
		<p class="mb-4 text-sm tracking-wide text-gray-400">© 2024. All rights reserved.</p>
	</div>
</footer>

<style lang="postcss">
	button {
		@apply block h-10 px-4 items-center
        text-cyan-800
        transition-colors bg-amber-100 hover:bg-amber-100/80
        rounded-full tracking-wider;
	}
</style>

// components/footer.tsx
import Link from "next/link";
import Image, { StaticImageData } from "next/image";
import Email from "@/static/email.png";
import InstagramLogo from "@/static/instagram.png";

export default function Footer() {
    return (
        <footer id="contact" className="px-8 bg-gray-900">
            <div className="m-auto w-full max-w-5xl">
                <div className="flex flex-wrap py-6 gap-8">
                    <FooterItem title="Contact">
                        <FooterSocial
                            image={{ src: Email, alt: "Email icon" }}
                            href="mailto:tabulamusica@cambridgesu.co.uk"
                        >
                            tabulamusica@cambridgesu.co.uk
                        </FooterSocial>
                        <FooterSocial
                            image={{
                                src: InstagramLogo,
                                alt: "Instagram logon",
                            }}
                            href="https://www.instagram.com/tabula_musica"
                        >
                            @tabula_musica
                        </FooterSocial>
                    </FooterItem>
                    <FooterItem title="Subscribe">
                        <div className="flex flex-wrap gap-4">
                            <FooterButton href="https://lists.srcf.net/mailman/listinfo">
                                Mailing&nbsp;List
                            </FooterButton>
                            <FooterButton href="/#contact">
                                Magazine
                            </FooterButton>
                        </div>
                    </FooterItem>
                </div>

                <hr className="border-neutral-600" />
                <p className="py-4 text-xs font-mono tracking-wide text-neutral-400">
                    © 2024 Tabula Musica. All rights reserved.
                </p>
            </div>
        </footer>
    );
}

function FooterItem({
    title,
    children,
}: {
    title: string;
    children: React.ReactNode;
}) {
    return (
        <hgroup className="grow">
            <h2 className="text-lg uppercase tracking-widest text-cyan-100">
                {title}
            </h2>
            <div className="py-4 font-mono text-neutral-200">{children}</div>
        </hgroup>
    );
}

function FooterSocial({
    image,
    href,
    children,
}: {
    image: { src: StaticImageData; alt: string };
    href: string;
    children: React.ReactNode;
}) {
    return (
        <p>
            <Image
                className="inline"
                src={image.src}
                alt={image.alt}
                width={20}
            />
            &nbsp;
            <Link className="tracking-tighter hover:underline" href={href}>
                {children}
            </Link>
        </p>
    );
}

function FooterButton({
    href,
    children,
}: {
    href: string;
    children: React.ReactNode;
}) {
    return (
        <Link
            className="px-4 py-2 rounded-full tracking-wider font-serif text-cyan-800 transition-colors bg-amber-100 hover:bg-amber-100/90"
            href={href}
        >
            {children}
        </Link>
    );
}
