// app/profile/page.tsx
import { getSessionUserProfile } from "@/app/lib/session";
import { signOut } from "@/auth";

export default async function ProfilePage() {
    const { user, profile } = await getSessionUserProfile();

    if (!user || !profile) {
        return (
            <main>
                <div className="py-16 text-5xl text-center text-cyan-800">
                    Please sign in:
                    <br />
                    <form>
                        <a href="/login">Sign in</a>
                    </form>
                </div>
            </main>
        );
    }

    return (
        <main>
            <div className="py-16 text-5xl text-center text-cyan-800">
                Hello, {profile.name}!
                <br />
                Logged in as {user.email}
                <br />
                <form
                    action={async () => {
                        "use server";
                        await signOut();
                    }}
                >
                    <button>Sign out</button>
                </form>
            </div>
        </main>
    );
}

// src/lib/components/header/mod/Profile.svelte
<script lang="ts">
    import { page } from "$app/state";

    const user = page.data.user;
</script>

<div class="py-1">
    {#if user}
        <a
            class="inline-flex h-8 my-1 px-4 min-w-fit items-center rounded-full transition-colors bg-black/10 hover:bg-violet-900 text-violet-900 hover:text-white"
            href="/profile"
            draggable="false"
        >
            {user?.name}
        </a>
    {:else}
        <form action="/auth/google">
            <button
                class="inline-flex h-8 my-1 px-4 min-w-fit items-center rounded-full transition-colors bg-black/10 hover:bg-violet-900 text-violet-900 hover:text-white"
            >
                Sign in
            </button>
        </form>
    {/if}
</div>
