// components/search.tsx
"use client";

import { handleSearch } from "@/app/lib/actions";
import { useSearchParams } from "next/navigation";

export default function Search() {
    const searchParams = useSearchParams();
    return (
        <search className="absolute right-4 h-full py-1 max-sm:hidden">
            <form className="h-full" action={handleSearch}>
                <input
                    name="search"
                    className="h-full px-4 w-36 focus:w-48 text-cyan-800 bg-black/5 outline-none rounded-lg border border-transparent transition-all focus:border-gray-400 focus:bg-black/10 placeholder:text-gray-500 focus:placeholder:text-gray-600"
                    placeholder="Search articles..."
                    defaultValue={searchParams.get("q") ?? ""}
                />
            </form>
        </search>
    );
}

// src/lib/components/header/mod/Search.svelte
<script>
	import { page } from '$app/stores';

	let query = $page.url.searchParams.get('q');
</script>

<search class="grow h-12">
	<form class="relative h-10 py-1" action="/search">
		<img class="absolute left-2 inset-y-4 size-5" src="/search.svg" alt="" />
		<input name="q" class="input" placeholder="Search…" autocomplete="off" value={query} required />
	</form>
</search>

<style>
	input {
		@apply w-full max-w-36 xs:max-w-44 sm:max-w-64
		text-xl	tracking-wide
		pl-9 rounded-full;
	}
</style>
