// src/lib/components/Footer.svelte
<footer class="bg-gray-900">
	<div class="mx-auto max-w-6xl px-6">
		<div class="grid sm:grid-cols-2 py-6 gap-8">
			<!-- <hgroup class="grow">
				<h4 class="mb-4 text-lg uppercase tracking-widest text-cyan-100">Subscribe</h4>
				<p class="mb-4 text-gray-200">From £0/month</p>
				<div class="flex flex-wrap gap-4">
					<button>Mailing list</button>
					<button>Paper edition</button>
				</div>
			</hgroup>
			<hgroup class="grow">
				<h4 class="mb-4 text-lg uppercase tracking-widest text-cyan-100">Write</h4>
				<p class="mb-4 text-gray-200">Become an editor maybe</p>
				<button>Apply</button>
			</hgroup> -->
			<hgroup class="grow">
				<h4 class="mb-4 text-lg uppercase tracking-widest text-cyan-100">Contact</h4>
				<p class="mb-4 text-gray-200">Have any questions, or fancy writing for us?</p>
				<button>Contact</button>
			</hgroup>
			<hgroup class="grow">
				<h4 class="mb-4 text-lg uppercase tracking-widest text-cyan-100">Social</h4>
				<p>
					<img
						class="inline mr-1 size-4"
						src="/icons/instagram.png"
						alt="Instagram logo"
						width={20}
					/>
					<a
						class="tracking-wide transition-colors text-gray-200 hover:text-white"
						href="https://www.instagram.com/tabula_musica"
					>
						@tabula_musica
					</a>
				</p>
				<p>
					<img class="inline mr-1 size-4" src="/icons/email.png" alt="Email icon" />
					<a
						class="tracking-wide transition-colors text-gray-200 hover:text-white"
						href="mailto:tabulamusica@cambridgesu.co.uk"
					>
						tabulamusica@cambridgesu.co.uk
					</a>
				</p>
			</hgroup>
			<hgroup class="grow">
				<h4 class="mb-4 text-lg uppercase tracking-widest text-cyan-100">Donate</h4>
				<p class="mb-4 text-gray-200">Give money</p>
				<button>Donate</button>
			</hgroup>
			<!-- Donate button -->
		</div>
		<hr class="mb-4 border-neutral-600" />
		<ul class="mb-4 flex gap-x-8 text-sm text-gray-400">
			<li>
				<a href="/about">About</a>
			</li>
			<li>
				<a href="/privacy-policy">Privacy policy</a>
			</li>
			<li>
				<a href="/cookies">Cookies</a>
			</li>
			<li>
				<a href="/advertising">Advertising</a>
			</li>
		</ul>
		<p class="mb-4 text-sm tracking-wide text-gray-400">© 2024. All rights reserved.</p>
	</div>
</footer>

<style lang="postcss">
	button {
		@apply block h-10 px-4 items-center
        text-cyan-800
        transition-colors bg-amber-100 hover:bg-amber-100/80
        rounded-full tracking-wider;
	}
</style>

// app/ui/footer.tsx
import Link from "next/link";
import Image from "next/image";
import InstagramLogo from "/public/social/instagram.png";

export default function Footer() {
    return (
        <footer id="contact" className="px-8 bg-gray-900">
            <div className="m-auto w-full max-w-5xl">
                <Contact />
                <hr className="border-neutral-600" />
                <Legal />
            </div>
        </footer>
    );
}

function Contact() {
    return (
        <div className="flex max-sm:flex-col py-6">
            <div className="grow min-w-80">
                <h2 className="text-lg font-serif uppercase tracking-widest text-cyan-100/80">
                    Contact
                </h2>
                <div className="py-4 font-mono text-neutral-200">
                    <p>
                        <Link
                            className="hover:underline"
                            href="mailto:tabulamusica@cambridgesu.co.uk"
                        >
                            tabulamusica@cambridgesu.co.uk
                        </Link>
                    </p>
                    <p>
                        <Link
                            className="group"
                            href="https://www.instagram.com/tabula_musica"
                        >
                            <Image
                                className="inline"
                                src={InstagramLogo}
                                alt="Instagram logo"
                                width={20}
                            />{" "}
                            <span className="group-hover:underline">
                                @tabula_musica
                            </span>
                        </Link>
                    </p>
                </div>
            </div>
            <div className="grow">
                <h3 className="text-lg font-serif uppercase tracking-widest text-cyan-100/80">
                    Subscribe
                </h3>
                <div className="flex sm:max-md:flex-col gap-4 py-4 text-lg text-neutral-200">
                    <p>
                        <Link
                            className="px-4 py-2 rounded-full tracking-wider font-serif text-cyan-800 transition-colors bg-amber-100 hover:bg-amber-100/90"
                            href="https://lists.srcf.net/mailman/listinfo"
                        >
                            Mailing&nbsp;List
                        </Link>
                    </p>
                    <p>
                        <Link
                            className="px-4 py-2 rounded-full tracking-wider font-serif text-cyan-800 transition-colors bg-amber-100 hover:bg-amber-100/90"
                            href="/#contact"
                        >
                            Magazine
                        </Link>
                    </p>
                </div>
            </div>
        </div>
    );
}

function Legal() {
    return (
        <p className="py-4 text-xs font-mono tracking-wide text-neutral-400">
            © 2024 Tabula Musica. All rights reserved.
        </p>
    );
}
