// src/routes/login/+page.svelte
<script lang="ts">
	import { enhance } from '$app/forms';
	import { fade } from 'svelte/transition';
	import type { ActionData } from './$types';
	import { signIn } from '@auth/sveltekit/client';
	// import { sign } from 'crypto';

	export let form: ActionData;
</script>

<div class="max-w-4xl p-8">
	<button on:click={() => signIn('google')}>Sign in with Raven</button>
	<form method="POST" action="?/login" use:enhance>
		{#if form?.type === 'login'}
			{#if form?.incomplete}
				<p class="text-red-500" transition:fade>Please fill in all fields!</p>
			{:else if form?.invalid}
				<p class="text-red-500" transition:fade>Invalid credentials!</p>
			{/if}
		{/if}

		<input class="input" type="email" name="email" placeholder="Email" required />
		<input class="input" type="password" name="password" placeholder="Password" required />
		<button>Log in</button>
	</form>
	<form method="POST" action="?/signup" use:enhance>
		{#if form?.type === 'signup'}
			{#if form?.incomplete}
				<p class="text-red-500" transition:fade>Please fill in all fields!</p>
			{:else if form?.invalid}
				<p class="text-red-500" transition:fade>Invalid credentials!</p>
			{:else if form?.alreadyExists}
				<p class="text-red-500" transition:fade>Email address already in use!</p>
			{:else if form?.invalid}
				<p class="text-red-500" transition:fade>Invalid credentials!</p>
			{/if}
		{/if}

		<input class="input" type="email" name="email" placeholder="Email" required />
		<input
			class="input"
			type="password"
			name="password"
			placeholder="Password"
			value="password"
			required
		/>
		<input
			class="input"
			type="password"
			name="confirmPassword"
			placeholder="Confirm password"
			required
		/>
		<input class="input" type="text" name="name" placeholder="Name" value="Jane Doe" required />
		<p>Would you like to subscribe to our mailing list?</p>
		<input class="block size-6" type="checkbox" name="mailingList" />
		<button>Sign up</button>
	</form>
</div>

<style lang="postcss">
	button {
		@apply h-10 px-4
        bg-black/5 hover:bg-black/20
        rounded-lg tracking-wider;
	}

	input,
	button,
	p {
		@apply mb-4;
	}
</style>

// app/login/page.tsx
import { SignInCredentials, SignUpCredentials, signIn, signUp } from "@/auth";
import prisma from "@/app/lib/database";
import { redirect } from "next/navigation";

export default function LoginPage() {
    async function handleSignIn(formData: FormData) {
        "use server";
        const credentials: SignInCredentials = {
            email: formData.get("email") as string,
            password: formData.get("password") as string,
        };
        const user = await signIn(credentials);
        if (user) redirect("/profile");
    }

    async function handleSignUp(formData: FormData) {
        "use server";
        const credentials: SignUpCredentials = {
            email: formData.get("email") as string,
            password: formData.get("password") as string,
            confirmPassword: formData.get("confirmPassword") as string,
            name: formData.get("name") as string,
            mailingList: formData.get("mailingList") === "on",
        };
        const user = await signUp(credentials);
        if (user) redirect("/profile");
    }

    return (
        <main>
            <div className="p-32">
                <form action={handleSignIn}>
                    <input
                        type="email"
                        name="email"
                        placeholder="Email"
                        required
                    />
                    <br />
                    <input
                        type="password"
                        name="password"
                        placeholder="Password"
                        defaultValue="password"
                        required
                    />
                    <br />
                    <button>Log in</button>
                </form>
                <br />
                <form action={handleSignUp}>
                    <input
                        type="email"
                        name="email"
                        placeholder="Email"
                        defaultValue="newuser@example.com"
                        required
                    />
                    <br />
                    <input
                        type="password"
                        name="password"
                        placeholder="Password"
                        defaultValue="password"
                        required
                    />
                    <br />
                    <input
                        type="password"
                        name="confirmPassword"
                        placeholder="Confirm password"
                        defaultValue="password"
                        required
                    />
                    <br />
                    <input
                        type="text"
                        name="name"
                        placeholder="Name"
                        defaultValue="Jane Doe"
                        required
                    />
                    <br />
                    Would you like to subscribe to our mailing list?
                    <br />
                    <input type="checkbox" name="mailingList" />
                    <br />
                    <button>Sign up</button>
                </form>
            </div>

            <button
                onClick={async () => {
                    "use server";
                    await prisma.reset();
                }}
            >
                Reset database
            </button>
        </main>
    );
}
